version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: db

  backend:
    image: artek22/foodgram_backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    container_name: foodgram_backend

  frontend:
    image: artek22/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - db_value:/var/lib/postgresql/data/

    depends_on:
      - backend
    container_name: foodgram_nginx

volumes:
  static_value:
  media_value:
  db_value:
